server:
  port: 8000                    # 指定该Eureka实例的端口
eureka:
  instance:
    hostname: localhost         # 指定该Eureka实例的主机名
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
